### ISSUE TITLE
API/ Open Source

### ISSUE THREAD

**Issue by billlyd123** [svidgen/mtg.deckanalyzer.com-Feedback#40] opened 2020-05-24 06:12 UTC
I am working on a school project to optimize decks and I was wondering if there was anyway I could access this code or some sort of API because a web interface wont work with machine learning algorithms.

**Comment by svidgen** [comment] 2020-05-24 16:05
Hi @billlyd123,

No time has really been spent on making the codebase ready for sharing, so I can't just share it with you, as-is. Part of the issue is simply that I haven't audited anything to know exactly what might be over shared. But, if you need some snippets to learn from, I could provide a few. Or if you need some guidance, I can help a little there too.

If you need card data, I just get mine from [mtgjson](https://mtgjson.com/).

What exactly are you looking for? What is the aim of your project specifically?

**Comment by billlyd123** [comment] 2020-05-24 20:25
I was hoping to get some sort of evaluation function to use as a heuristic. Something that taskes all the cards as input and produces some sort score

**Comment by billlyd123** [comment] 2020-05-24 20:34
^a deck of cards as input

**Comment by billlyd123** [comment] 2020-05-30 02:26
LMK what you think, also willing to discuss compensation

**Comment by svidgen** [comment] 2020-07-31 02:23
Hey @billlyd123,

Sorry for the late reply.

We use ML-esque techniques on our end, but I'm not sure I have anything that would help you (or *would have* helped you). Given a deck of cards and a set of related tactics, in addition to the basic static analyses (see [hypergeometric distribution](https://en.wikipedia.org/wiki/Hypergeometric_distribution) for example), we run a small [Monte Carlo simulation](https://en.wikipedia.org/wiki/Monte_Carlo_method) to produce the `P(All)` and `Average Shortage` numbers.

Our `pruning suggestions` do use card scoring data we've swagged on the backend using a very simple ML/regression combined with a very limited sample of cards sorted by "card power". This data is combined with a pretty simple heuristic for our `P(All)` which is effectively just the product of the individual success rates. But, this "card power" data set is very small, and the whole feature is very *beta*, so I wouldn't advise using it academically.

All that said, I'm not sure what I could have done to help in the end. Most of our work has been in creating the UI, the client-side Monte Carlo bits, and a few *very simplistic and **very beta*** ML-type stuff on the backend. But, it's nothing I can just hand over or give you an API for at this point.

I'm happy to continue the discussion if you still have the need, and if you can articulate exactly what you'd want out of an API. If it helps you, it could be of use to others too. (An API would *likely* have to be a paid service though... as I wouldn't have many monetization options for an API.)

I'm resolving this issue for now. Feel free to re-open if you still think we can help.

**Closed by svidgen** 2020-07-31 02:23 UTC
